config/routes.rb
Rails.application.routes.draw do

  resources :registrations, only: [:index, :new, :create] do
    collection do
      get :confirm_email
    end

    member do
      get :resend_email_confirmation
    end
  end

  resources :passwords, only: [:edit, :update]

  resources :dashboard, only: [:index] do
    collection do
      get :search
    end
  end

  resource :sessions, only: [:new, :create, :destroy]

  root 'pages#index'

  get '/test', to: "pages#test"
end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :users

  validates :name, presence: true

  # begin ClassMethods
  def self.provision!(reg)
    org = Organization.new do |f|
      f.name = reg.organization_name
    end

    create_admin_for_organization(reg, org) if org.save
  end

  def self.create_admin_for_organization(reg, org)
    admin = User.build_new_user({
      email: reg.email,
      role: 'admin'
    })

    admin.organization = org

    if admin.save
      reg.mark_as_registered!(org, admin)
      admin.confirm_email!
    end

    admin
  end
  # end ClassMethods

end

app/models/registration.rb
class Registration < ActiveRecord::Base

  validates :organization_name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :email_confirmation_token, uniqueness: true, presence: true

  belongs_to :user
  belongs_to :organization


  def confirm!
    touch(:confirmed_at) if !confirmed?
  end

  def expired?
    !confirmed? && (email_confirmation_sent_at < 24.hours.ago)
  end

  def confirmed?
    confirmed_at.present?
  end

  def set_confirmation_token
    self.email_confirmation_token = Service.reference_code(email)
  end

  def reset_confirmation_token
    self.email_confirmation_token = Service.reference_code(email)
  end

  def mark_as_registered!(org, admin)
    self.organization = org
    self.user         = admin
    self.save
  end

  def email_confirmation_sent_recently?
    !(registration_email_count < 5) && (email_confirmation_sent_at > 5.minute.ago)
  end

  def resend_email_confirmation!
    return if email_confirmation_sent_recently?
    RegistrationMailer.email_confirmation(self.id).deliver_now
  end
end

app/models/role.rb
class Role < ActiveRecord::Base

  ROLES = %w(admin analyst staff)

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, inclusion: {
    in: ROLES,
    message: 'Invalid role'
  }
end

app/models/tic.rb
class Tic
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  paginates_per 50

  field :event, type: String
  field :trace_id, type: Integer

  index({ event: 1 })
  index({ created_at: 1 })
  index({ trace_id: 1 })

  validates :event, presence: true
  validates :trace_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_one    :registration
  belongs_to :organization

  validates :email, presence: true
  validates :role, presence: true
  validates :role, inclusion: {
    in: Role::ROLES
  }

  validates :password, length: { minimum: 6, maximum: 30 }, allow_nil: true

  Role::ROLES.each do |role|
    define_method "#{role}?".to_sym do
      self.role == role
    end
  end

  # class methods

    def self.build_new_user(user_params)
      User.new do |u|
        u.email = user_params[:email].downcase
        u.name  = user_params[:name]
        u.role  = user_params[:role]
        u.password                  = Service.random_key
        u.password_confirmation     = u.password
        u.email_confirmation_token  = Service.reference_code(u.email)
      end
    end
  # end of class methods

  def confirm_email!
    self.touch(:email_confirmed_at) if !email_confirmed?
  end

  def email_confirmed?
    self.email_confirmed_at.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home_path
    if user_signed_in?
      dashboard_index_path
    else
      root_path
    end
  end

  def user_signed_in?
    session[:user_id].present?
  end

  def current_user
    return if user_signed_in?
    @current_user ||= User.find(session[:user_id])
  end

  helper_method :home_path
  helper_method :user_signed_in?
  helper_method :current_user

  private

  def authenticate_user!
    redirect_to home_path unless user_signed_in?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @tics = Tic.page(params[:page])
  end

  def search
    @tics = SearchEngine.search(params[:query]).page(params[:page])
    render action: :index
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def test
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

  before_action :load_user

  def edit
  end

  def update
    if @user.update_attributes(password_params)
      redirect_to home_path, notice: 'Password updated successfully'
    else
      render :edit
    end
  end

  private

  def load_user
    @user = User.where(id: params[:id]).first
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  rescue_from InvalidEmailToken, with: :invalid_email_token

  def index
    @registrations = Registration.all
  end

  def new
    @reg = Registration.new
  end

  def create
    @reg = Registration.new(registration_params)
    @reg.set_confirmation_token

    if @reg.save
      RegistrationMailer.email_confirmation(@reg.id).deliver_now
    else
      render 'new'
    end
  end

  def resend_email_confirmation
    @reg = Registration.find(params[:id])
    @reg.resend_email_confirmation!
    render action: :create
  end

  def confirm_email
    load_registration

    if @reg.expired?
      redirect_to root_path, notice: I18n.t(:email_token_expired)
    elsif @reg.confirm!
      admin = Organization.provision!(@reg)
      redirect_to edit_password_path(admin), notice: I18n.t(:email_confirmed)
    else
      redirect_to root_path, notice: I18n.t(:email_already_confirmed)
    end
  end

  private

  def registration_params
    params.require(:registration).permit(:email, :organization_name)
  end

  def load_registration
    return nil if params[:email_confirmation_token].blank?
    @reg = Registration.where(email_confirmation_token: params[:email_confirmation_token]).first
    raise InvalidEmailToken if @reg.blank?
  end

  def invalid_email_token
    redirect_to root_path, notice: I18n.t(:invalid_email_token)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.where(email: login_params[:email]).first

    if @user && @user.authenticate(login_params[:password])
      set_user_login_session
      redirect_to home_path
    else
      redirect_to :back
    end
  end

  def destroy
    session.clear
    redirect_to home_path
  end

  private

  def login_params
    params.require(:session).permit(:email, :password)
  end

  def set_user_login_session
    session[:user_id] = @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display(tic)
    attr = tic.attributes
    attr.delete("_id")
    output = attr.to_a.map do |item|
      "<span class='tic-left'>#{item.first}</span> = <span clss='tic-right'>#{item.last}</span>"
    end.join(" ")

    "<div class='tic'>#{output}</div>".html_safe
  end
end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class="search-wrapper card">
      <form id="tic-search-form" action="<%= search_dashboard_index_path %>" method="get">
        <input id="search" autocomplete="off" placeholder="Search here" name="query">
        <i id="tic-search-icon" class="material-icons">search</i>
      </form>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m12">
    <div class="chip">Total <%= @tics.count %> events found. </div>
    <%= paginate @tics %>
    <ul class="collection">
      <% @tics.each do |tic| %>
        <li class="collection-item"><%= display(tic) %></li>
      <% end %>
    </ul>
    <%= paginate @tics %>
  </div>
</div>

<div class="row">
  <div class="col s12 m3">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Card Title</span>
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Ticman</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <!-- CSS  -->
    <!--
      <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
      <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
     -->

  </head>

  <body>
    <%= render 'shared/header' %>

    <% if notice.present? %>
      <div class="chip"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="chip"><%= alert %></div>
    <% end %>

    <!-- <div class="container"> -->
      <%= yield %>
    <!-- </div> -->

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Ticman</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- CSS  -->
  <!--
    <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
   -->

</head>
  <body>
    <%= render 'shared/dashboard_header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <!-- <div class="container"> -->
      <%= yield %>
    <!-- </div> -->

    <%= render 'shared/dashboard_footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center orange-text">Ticman</h1>
    <div class="row center">
      <h5 class="header col s12 light">Yet another event logger</h5>
    </div>
    <div class="row center">
      <%= link_to 'Create organization', new_registration_path, id: "download-button", class: "btn-large waves-effect waves-light orange" %>
    </div>
    <br><br>

  </div>
</div>

<div class="section">

</div>

app/views/shared/_dashboard_footer.html.erb
<footer class="page-footer white">
  <div class="footer-copyright orange center">
    Made with <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
  </div>
</footer>

app/views/shared/_dashboard_header.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">settings</a></li>
  <li class="divider"></li>
  <li><a href="<%= sessions_path %>" data-method="DELETE">Logout</a></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">&nbsp;Ticman</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="#!">
         <input type="date" class="datepicker" placeholder="From">
      </a></li>
      <li><a href="#!">
        <input type="date" class="datepicker" placeholder="To">
      </a></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons right">settings</i></a></li>
    </ul>
  </div>
</nav>

app/views/shared/_footer.html.erb
<footer class="page-footer orange">
  <div class="footer-copyright">
    <div class="container center">
    Made with
    <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper"><a id="logo-container" href="<%= home_path %>" class="brand-logo">&nbsp;Ticman</a>
    <ul class="right hide-on-med-and-down">
      <li>
        <% if user_signed_in? %>
          <a href="<%= sessions_path %>" data-method="DELETE">Logout</a>
        <% else %>
          <a href="<%= new_sessions_path %>">Login</a>
        <% end %>
      </li>
    </ul>
  </div>
</nav>